// Dados do Baralho Cigano (36 Cartas)
const baralhoCigano = [
    { id: 1, nome: "O Cavaleiro", significado: "Movimento, notícias rápidas e coragem para agir." },
    { id: 2, nome: "O Trevo", significado: "Pequenos problemas, mas que trazem sorte e aprendizado após superados." },
    { id: 3, nome: "O Navio", significado: "Mudanças, viagens, novos horizontes e projetos a longo prazo." },
    { id: 4, nome: "A Casa", significado: "Equilíbrio familiar, estabilidade e o seu porto seguro." },
    { id: 5, nome: "A Árvore", significado: "Saúde, vitalidade e crescimento sólido." },
    { id: 6, nome: "As Nuvens", significado: "Confusão mental, dúvidas e incertezas passageiras." },
    { id: 7, nome: "A Serpente", significado: "Atenção com traições ou pessoas mal-intencionadas ao redor." },
    { id: 8, nome: "O Caixão", significado: "Finais necessários para que novos começos aconteçam. Transformação." },
    { id: 9, nome: "As Flores", significado: "Felicidade, alegria, presentes e reconhecimento social." },
    { id: 10, nome: "A Foice", significado: "Cortes bruscos, decisões rápidas e colheita do que foi plantado." },
    { id: 11, nome: "O Chicote", significado: "Conflitos, discussões ou necessidade de disciplina e poder." },
    { id: 12, nome: "Os Pássaros", significado: "Comunicação, parcerias, paquera e alegria nas pequenas coisas." },
    { id: 13, nome: "A Criança", significado: "Inocência, novos começos, espontaneidade e imaturidade." },
    { id: 14, nome: "A Raposa", significado: "Estratégia, cautela e inteligência. Cuidado com armadilhas." },
    { id: 15, nome: "O Urso", significado: "Proteção, mas também pode indicar ciúmes ou sobrecarga de energia." },
    { id: 16, nome: "A Estrela", significado: "Esperança, brilho pessoal, proteção espiritual e sucesso." },
    { id: 17, nome: "A Cegonha", significado: "Novidades, mudanças positivas e novos ciclos de vida." },
    { id: 18, nome: "O Cachorro", significado: "Lealdade, amizade sincera e confiança." },
    { id: 19, nome: "A Torre", significado: "Isolamento necessário, autoconhecimento ou questões espirituais." },
    { id: 20, nome: "O Jardim", significado: "Vida social, eventos, colheita pública e lazer." },
    { id: 21, nome: "A Montanha", significado: "Desafios, bloqueios ou algo que exige esforço para ser superado." },
    { id: 22, nome: "O Caminho", significado: "Escolhas, livre-arbítrio e a necessidade de tomar uma decisão." },
    { id: 23, nome: "O Rato", significado: "Desgaste energético, pequenas perdas ou estresse." },
    { id: 24, nome: "O Coração", significado: "Amor, sentimentos profundos, paixão e entrega emocional." },
    { id: 25, nome: "O Anel", significado: "Alianças, contratos, compromissos e uniões (afetivas ou profissionais)." },
    { id: 26, nome: "Os Livros", significado: "Segredos, estudos, conhecimento e busca pela verdade." },
    { id: 27, nome: "A Carta", significado: "Documentos, mensagens escritas e notícias oficiais." },
    { id: 28, nome: "O Cigano", significado: "Energia masculina, ação ou uma figura masculina importante." },
    { id: 29, nome: "A Cigana", significado: "Energia feminina, intuição ou uma figura feminina importante." },
    { id: 30, nome: "Os Lírios", significado: "Paz, pureza, maturidade e harmonia." },
    { id: 31, nome: "O Sol", significado: "Sucesso absoluto, energia, clareza e prosperidade." },
    { id: 32, nome: "A Lua", significado: "Intuição, mistério, reconhecimento e as fases emocionais." },
    { id: 33, nome: "A Chave", significado: "Soluções, abertura de caminhos e a resposta que você procura." },
    { id: 34, nome: "Os Peixes", significado: "Prosperidade financeira, lucros e abundância material." },
    { id: 35, nome: "A Âncora", significado: "Segurança, estabilidade e metas alcançadas." },
    { id: 36, nome: "A Cruz", significado: "Fé, vitória final após o sacrifício e destino." }
];

// Dados do Tarot (Arcanos Maiores)
const tarot = [
    { id: 1, nome: "O Louco", significado: "Liberdade, espontaneidade e o início de uma jornada desconhecida." },
    { id: 2, nome: "O Mago", significado: "Habilidade, força de vontade e poder para manifestar seus desejos." },
    { id: 3, nome: "A Sacerdotisa", significado: "Mistério, intuição, sabedoria silenciosa e o que está oculto." },
    { id: 4, nome: "A Imperatriz", significado: "Abundância, fertilidade, natureza e o poder criativo feminino." },
    { id: 5, nome: "O Imperador", significado: "Autoridade, estrutura, estabilidade e a figura paterna ou líder." },
    { id: 6, nome: "O Hierofante", significado: "Tradição, espiritualidade institucional, ensino e valores morais." },
    { id: 7, nome: "Os Enamorados", significado: "Escolhas do coração, amor, união e harmonia de valores." },
    { id: 8, nome: "O Carro", significado: "Determinação, vitória, controle e progresso acelerado." },
    { id: 9, nome: "A Justiça", significado: "Equilíbrio, verdade, causa e efeito, responsabilidade." },
    { id: 10, nome: "O Eremita", significado: "Busca interior, solidão produtiva, introspecção e guia espiritual." },
    { id: 11, nome: "A Roda da Fortuna", significado: "Ciclos, destino, mudanças repentinas e a sorte girando." },
    { id: 12, nome: "A Força", significado: "Domínio das paixões, coragem mansa e resistência espiritual." },
    { id: 13, nome: "O Pendurado", significado: "Sacrifício, pausa necessária e olhar as coisas por outro ângulo." },
    { id: 14, nome: "A Morte", significado: "Transformação profunda, renascimento e o fim de um ciclo." },
    { id: 15, nome: "A Temperança", significado: "Paciência, moderação, cura e equilíbrio das emoções." },
    { id: 16, nome: "O Diabo", significado: "Vícios, apego material, sombras e tentações do ego." },
    { id: 17, nome: "A Torre", significado: "Ruptura brusca, queda de estruturas falsas e revelação da verdade." },
    { id: 18, nome: "A Estrela", significado: "Inspiração, renovação, esperança e paz espiritual." },
    { id: 19, nome: "A Lua", significado: "Ilusões, medos subconscientes e a necessidade de clareza." },
    { id: 20, nome: "O Sol", significado: "Alegria, vitalidade, sucesso e iluminação." },
    { id: 21, nome: "O Julgamento", significado: "Chamado interior, acerto de contas e despertar espiritual." },
    { id: 22, nome: "O Mundo", significado: "Conclusão, realização total, integração e sucesso final." }
];