const baralhoCigano = [
    { id: 1, nome: "O Cavaleiro", significado: "Movimento, notícias rápidas e coragem para agir.", imagem: "img/cigano/carta1.jpg" },
    { id: 2, nome: "O Trevo", significado: "Pequenos problemas, mas que trazem sorte e aprendizado.", imagem: "img/cigano/carta2.jpg" },
    { id: 3, nome: "O Navio", significado: "Mudanças, viagens, novos horizontes e projetos a longo prazo.", imagem: "img/cigano/carta3.jpg" },
    { id: 4, nome: "A Casa", significado: "Equilíbrio familiar, estabilidade e o seu porto seguro.", imagem: "img/cigano/carta4.jpg" },
    { id: 5, nome: "A Árvore", significado: "Saúde, vitalidade e crescimento sólido.", imagem: "img/cigano/carta5.jpg" },
    { id: 6, nome: "As Nuvens", significado: "Confusão mental, dúvidas e incertezas passageiras.", imagem: "img/cigano/carta6.jpg" },
    { id: 7, nome: "A Serpente", significado: "Atenção com traições ou pessoas mal-intencionadas ao redor.", imagem: "img/cigano/carta7.jpg" },
    { id: 8, nome: "O Caixão", significado: "Finais necessários para que novos começos aconteçam. Transformação.", imagem: "img/cigano/carta8.jpg" },
    { id: 9, nome: "As Flores", significado: "Felicidade, alegria, presentes e reconhecimento social.", imagem: "img/cigano/carta9.jpg" },
    { id: 10, nome: "A Foice", significado: "Cortes bruscos, decisões rápidas e colheita do que foi plantado.", imagem: "img/cigano/carta10.jpg" },
    { id: 11, nome: "O Chicote", significado: "Conflitos, discussões ou necessidade de disciplina e poder.", imagem: "img/cigano/carta11.jpg" },
    { id: 12, nome: "Os Pássaros", significado: "Comunicação, parcerias, paquera e alegria nas pequenas coisas.", imagem: "img/cigano/carta12.jpg" },
    { id: 13, nome: "A Criança", significado: "Inocência, novos começos, espontaneidade e imaturidade.", imagem: "img/cigano/carta13.jpg" },
    { id: 14, nome: "A Raposa", significado: "Estratégia, cautela e inteligência. Cuidado com armadilhas.", imagem: "img/cigano/carta14.jpg" },
    { id: 15, nome: "O Urso", significado: "Proteção, mas também pode indicar ciúmes ou sobrecarga de energia.", imagem: "img/cigano/carta15.jpg" },
    { id: 16, nome: "A Estrela", significado: "Esperança, brilho pessoal, proteção espiritual e sucesso.", imagem: "img/cigano/carta16.jpg" },
    { id: 17, nome: "A Cegonha", significado: "Novidades, mudanças positivas e novos ciclos de vida.", imagem: "img/cigano/carta17.jpg" },
    { id: 18, nome: "O Cachorro", significado: "Lealdade, amizade sincera e confiança.", imagem: "img/cigano/carta18.jpg" },
    { id: 19, nome: "A Torre", significado: "Isolamento necessário, autoconhecimento ou questões espirituais.", imagem: "img/cigano/carta19.jpg" },
    { id: 20, nome: "O Jardim", significado: "Vida social, eventos, colheita pública e lazer.", imagem: "img/cigano/carta20.jpg" },
    { id: 21, nome: "A Montanha", significado: "Desafios, bloqueios ou algo que exige esforço para ser superado.", imagem: "img/cigano/carta21.jpg" },
    { id: 22, nome: "O Caminho", significado: "Escolhas, livre-arbítrio e a necessidade de tomar uma decisão.", imagem: "img/cigano/carta22.jpg" },
    { id: 23, nome: "O Rato", significado: "Desgaste energético, pequenas perdas ou estresse.", imagem: "img/cigano/carta23.jpg" },
    { id: 24, nome: "O Coração", significado: "Amor, sentimentos profundos, paixão e entrega emocional.", imagem: "img/cigano/carta24.jpg" },
    { id: 25, nome: "O Anel", significado: "Alianças, contratos, compromissos e uniões (afetivas ou profissionais).", imagem: "img/cigano/carta25.jpg" },
    { id: 26, nome: "Os Livros", significado: "Segredos, estudos, conhecimento e busca pela verdade.", imagem: "img/cigano/carta26.jpg" },
    { id: 27, nome: "A Carta", significado: "Documentos, mensagens escritas e notícias oficiais.", imagem: "img/cigano/carta27.jpg" },
    { id: 28, nome: "O Cigano", significado: "Energia masculina, ação ou uma figura masculina importante.", imagem: "img/cigano/carta28.jpg" },
    { id: 29, nome: "A Cigana", significado: "Energia feminina, intuição ou uma figura feminina importante.", imagem: "img/cigano/carta29.jpg" },
    { id: 30, nome: "Os Lírios", significado: "Paz, pureza, maturidade e harmonia.", imagem: "img/cigano/carta30.jpg" },
    { id: 31, nome: "O Sol", significado: "Sucesso absoluto, energia, clareza e prosperidade.", imagem: "img/cigano/carta31.jpg" },
    { id: 32, nome: "A Lua", significado: "Intuição, mistério, reconhecimento e as fases emocionais.", imagem: "img/cigano/carta32.jpg" },
    { id: 33, nome: "A Chave", significado: "Soluções, abertura de caminhos e a resposta que você procura.", imagem: "img/cigano/carta33.jpg" },
    { id: 34, nome: "Os Peixes", significado: "Prosperidade financeira, lucros e abundância material.", imagem: "img/cigano/carta34.jpg" },
    { id: 35, nome: "A Âncora", significado: "Segurança, estabilidade e metas alcançadas.", imagem: "img/cigano/carta35.jpg" },
    { id: 36, nome: "A Cruz", significado: "Fé, vitória final após o sacrifício e destino.", imagem: "img/cigano/carta36.jpg" }
];

const tarot = [
    { id: 1, nome: "O Louco", significado: "Novos começos, espontaneidade, fé no universo e livre-arbítrio.", imagem: "img/tarot/0-o-louco.jpg" },
    { id: 2, nome: "O Mago", significado: "Poder, habilidade, concentração e ação.", imagem: "img/tarot/1-o-mago.jpg" },
    { id: 3, nome: "A Alta Sacerdotisa", significado: "Intuição, mistério, conhecimento oculto e o inconsciente.", imagem: "img/tarot/2-a-alta-sacerdotisa.jpg" },
    { id: 4, nome: "A Imperatriz", significado: "Fertilidade, natureza, abundância e maternidade.", imagem: "img/tarot/3-a-imperatriz.jpg" },
    { id: 5, nome: "O Imperador", significado: "Autoridade, estrutura, controle e poder.", imagem: "img/tarot/4-o-imperador.jpg" },
    { id: 6, nome: "O Hierofante", significado: "Tradição, espiritualidade, conformidade e crenças.", imagem: "img/tarot/5-o-hierofante.jpg" },
    { id: 7, nome: "Os Enamorados", significado: "Amor, harmonia, relacionamentos e escolhas importantes.", imagem: "img/tarot/6-os-enamorados.jpg" },
    { id: 8, nome: "O Carro", significado: "Controle, força de vontade, vitória e ação.", imagem: "img/tarot/7-o-carro.jpg" },
    { id: 9, nome: "A Força", significado: "Coragem, controle, compaixão e força interior.", imagem: "img/tarot/8-a-forca.jpg" },
    { id: 10, nome: "O Eremita", significado: "Introspecção, busca pela verdade, solidão e sabedoria.", imagem: "img/tarot/9-o-eremita.jpg" },
    { id: 11, nome: "A Roda da Fortuna", significado: "Destino, mudança, ciclos e boa sorte.", imagem: "img/tarot/10-a-roda-da-fortuna.jpg" },
    { id: 12, nome: "A Justiça", significado: "Equilíbrio, causa e efeito, verdade e justiça.", imagem: "img/tarot/11-a-justica.jpg" },
    { id: 13, nome: "O Pendurado", significado: "Sacrifício, nova perspectiva, suspensão e pausa.", imagem: "img/tarot/12-o-pendurado.jpg" },
    { id: 14, nome: "A Morte", significado: "Fim de um ciclo, transformação, transição e novos começos.", imagem: "img/tarot/13-a-morte.jpg" },
    { id: 15, nome: "A Temperança", significado: "Moderação, equilíbrio, paciência e harmonia.", imagem: "img/tarot/14-a-temperanca.jpg" },
    { id: 16, nome: "O Diabo", significado: "Apego material, tentação, dependência e sombras.", imagem: "img/tarot/15-o-diabo.jpg" },
    { id: 17, nome: "A Torre", significado: "Mudança repentina, caos, revelação e libertação.", imagem: "img/tarot/16-a-torre.jpg" },
    { id: 18, nome: "A Estrela", significado: "Esperança, inspiração, serenidade e fé no futuro.", imagem: "img/tarot/17-a-estrela.jpg" },
    { id: 19, nome: "A Lua", significado: "Ilusão, medo, intuição e enganos.", imagem: "img/tarot/18-a-lua.jpg" },
    { id: 20, nome: "O Sol", significado: "Sucesso, alegria, vitalidade e clareza.", imagem: "img/tarot/19-o-sol.jpg" },
    { id: 21, nome: "O Julgamento", significado: "Renascimento, chamado interior, absolvição e despertar.", imagem: "img/tarot/20-o-julgamento.jpg" },
    { id: 22, nome: "O Mundo", significado: "Conclusão, plenitude, sucesso e integração.", imagem: "img/tarot/21-o-mundo.jpg" },
    { id: 23, nome: "As de Copas", significado: "Amor, novos sentimentos, intuição, alegria emocional.", imagem: "img/tarot/as-de-copas.jpg" },
    { id: 24, nome: "Dois de Copas", significado: "União, parceria, conexão emocional, reconciliação.", imagem: "img/tarot/dois-de-copas.jpg" },
    { id: 25, nome: "Três de Copas", significado: "Celebração, amizade, comunidade, alegria compartilhada.", imagem: "img/tarot/tres-de-copas.jpg" },
    { id: 26, nome: "Quatro de Copas", significado: "Apatia, tédio, contemplação, recusar oportunidades.", imagem: "img/tarot/quatro-de-copas.jpg" },
    { id: 27, nome: "Cinco de Copas", significado: "Luto, perda, decepção ou foco no que foi perdido em vez do que resta.", imagem: "img/tarot/cinco-de-copas.jpg" },
    { id: 28, nome: "Seis de Copas", significado: "Nostalgia, memórias felizes, inocência, reencontro.", imagem: "img/tarot/seis-de-copas.jpg" },
    { id: 29, nome: "Sete de Copas", significado: "Ilusões, escolhas, desejos, fantasias e opções.", imagem: "img/tarot/sete-de-copas.jpg" },
    { id: 30, nome: "Oito de Copas", significado: "Abandono, deixar para trás, busca espiritual, afastamento.", imagem: "img/tarot/oito-de-copas.jpg" },
    { id: 31, nome: "Nove de Copas", significado: "Satisfação, desejos realizados, bem-estar e alegria.", imagem: "img/tarot/nove-de-copas.jpg" },
    { id: 32, nome: "Dez de Copas", significado: "Felicidade familiar, harmonia, alegria e paz duradoura.", imagem: "img/tarot/dez-de-copas.jpg" },
    { id: 33, nome: "Valete de Copas", significado: "Mensagens afetivas, criatividade, sensibilidade e novos começos emocionais.", imagem: "img/tarot/valete-de-copas.jpg" },
    { id: 34, nome: "Cavaleiro de Copas", significado: "Proposta romântica, convite, diplomacia e seguir os sentimentos.", imagem: "img/tarot/cavaleiro-de-copas.jpg" },
    { id: 35, nome: "Rainha de Copas", significado: "Compaixão, intuição, empatia e cuidado emocional.", imagem: "img/tarot/rainha-de-copas.jpg" },
    { id: 36, nome: "Rei de Copas", significado: "Equilíbrio emocional, diplomacia, controle dos sentimentos e generosidade.", imagem: "img/tarot/rei-de-copas.jpg" },
    { id: 37, nome: "As de Espadas", significado: "Clareza mental, novas ideias, triunfo sobre a adversidade e verdade.", imagem: "img/tarot/as-de-espadas.jpg" },
    { id: 38, nome: "Dois de Espadas", significado: "Dilema, impasse, indecisão e necessidade de escolha.", imagem: "img/tarot/dois-de-espadas.jpg" },
    { id: 39, nome: "Três de Espadas", significado: "Dor, tristeza, separação e decepção emocional.", imagem: "img/tarot/tres-de-espadas.jpg" },
    { id: 40, nome: "Quatro de Espadas", significado: "Descanso, meditação, recuperação e pausa estratégica.", imagem: "img/tarot/quatro-de-espadas.jpg" },
    { id: 41, nome: "Cinco de Espadas", significado: "Derrota, conflito, traição, competição desleal e isolamento.", imagem: "img/tarot/cinco-de-espadas.jpg" },
    { id: 42, nome: "Seis de Espadas", significado: "Transição, viagem mental, deixar o passado e ir em direção à calmaria.", imagem: "img/tarot/seis-de-espadas.jpg" },
    { id: 43, nome: "Sete de Espadas", significado: "Estratégia, cautela, segredos e inteligência tática.", imagem: "img/tarot/sete-de-espadas.jpg" },
    { id: 44, nome: "Oito de Espadas", significado: "Restrição, aprisionamento mental, impotência e autocrítica.", imagem: "img/tarot/oito-de-espadas.jpg" },
    { id: 45, nome: "Nove de Espadas", significado: "Ansiedade, pesadelos, desespero, medo e preocupação excessiva.", imagem: "img/tarot/nove-de-espadas.jpg" },
    { id: 46, nome: "Dez de Espadas", significado: "Fim de ciclo doloroso, traição, ruína e alívio final.", imagem: "img/tarot/dez-de-espadas.jpg" },
    { id: 47, nome: "Valete de Espadas", significado: "Vigilância, novas ideias, curiosidade e comunicação direta.", imagem: "img/tarot/valete-de-espadas.jpg" },
    { id: 48, nome: "Cavaleiro de Espadas", significado: "Ação rápida, ambição, assertividade e impulsividade mental.", imagem: "img/tarot/cavaleiro-de-espadas.jpg" },
    { id: 49, nome: "Rainha de Espadas", significado: "Clareza de pensamento, independência, inteligência e objetividade.", imagem: "img/tarot/rainha-de-espadas.jpg" },
    { id: 50, nome: "Rei de Espadas", significado: "Autoridade, intelecto, lógica, discernimento e justiça.", imagem: "img/tarot/rei-de-espadas.jpg" },
    { id: 51, nome: "As de Ouros", significado: "Prosperidade, novas oportunidades materiais, abundância e fundação.", imagem: "img/tarot/as-de-ouros.jpg" },
    { id: 52, nome: "Dois de Ouros", significado: "Equilíbrio financeiro, adaptabilidade, lidar com múltiplas tarefas.", imagem: "img/tarot/dois-de-ouros.jpg" },
    { id: 53, nome: "Três de Ouros", significado: "Trabalho em equipe, planejamento, aprendizado e colaboração.", imagem: "img/tarot/tres-de-ouros.jpg" },
    { id: 54, nome: "Quatro de Ouros", significado: "Apego, avareza, controle, estabilidade material e segurança.", imagem: "img/tarot/quatro-de-ouros.jpg" },
    { id: 55, nome: "Cinco de Ouros", significado: "Dificuldade financeira, isolamento, preocupação e escassez material.", imagem: "img/tarot/cinco-de-ouros.jpg" },
    { id: 56, nome: "Seis de Ouros", significado: "Caridade, generosidade, partilha e sucesso financeiro.", imagem: "img/tarot/seis-de-ouros.jpg" },
    { id: 57, nome: "Sete de Ouros", significado: "Paciência, avaliação, investimento a longo prazo e colheita.", imagem: "img/tarot/sete-de-ouros.jpg" },
    { id: 58, nome: "Oito de Ouros", significado: "Dedicação, trabalho árduo, habilidade e foco nos detalhes.", imagem: "img/tarot/oito-de-ouros.jpg" },
    { id: 59, nome: "Nove de Ouros", significado: "Autossuficiência, sucesso material, independência e luxo.", imagem: "img/tarot/nove-de-ouros.jpg" },
    { id: 60, nome: "Dez de Ouros", significado: "Riqueza, herança, segurança e legado familiar.", imagem: "img/tarot/dez-de-ouros.jpg" },
    { id: 61, nome: "Valete de Ouros", significado: "Oportunidade financeira, estudo, planejamento e dedicação prática.", imagem: "img/tarot/valete-de-ouros.jpg" },
    { id: 62, nome: "Cavaleiro de Ouros", significado: "Trabalho constante, rotina, paciência e progresso financeiro.", imagem: "img/tarot/cavaleiro-de-ouros.jpg" },
    { id: 63, nome: "Rainha de Ouros", significado: "Praticidade, segurança, fertilidade e conexão com a natureza.", imagem: "img/tarot/rainha-de-ouros.jpg" },
    { id: 64, nome: "Rei de Ouros", significado: "Sucesso, riqueza, estabilidade, liderança e prosperidade material.", imagem: "img/tarot/rei-de-ouros.jpg" },
    { id: 65, nome: "As de Paus", significado: "Potencial criativo, entusiasmo, novos começos na carreira e inspiração.", imagem: "img/tarot/as-de-paus.jpg" },
    { id: 66, nome: "Dois de Paus", significado: "Planejamento, decisões futuras, visão de longo prazo e ambição.", imagem: "img/tarot/dois-de-paus.jpg" },
    { id: 67, nome: "Três de Paus", significado: "Expansão, exploração, visão e aguardando resultados.", imagem: "img/tarot/tres-de-paus.jpg" },
    { id: 68, nome: "Quatro de Paus", significado: "Celebração, estabilidade, lar, harmonia e alegria.", imagem: "img/tarot/quatro-de-paus.jpg" },
    { id: 69, nome: "Cinco de Paus", significado: "Competição, conflito, desacordo e obstáculos externos.", imagem: "img/tarot/cinco-de-paus.jpg" },
    { id: 70, nome: "Seis de Paus", significado: "Sucesso, reconhecimento, vitória pública e confiança.", imagem: "img/tarot/seis-de-paus.jpg" },
    { id: 71, nome: "Sete de Paus", significado: "Defesa, resistência, manter sua posição e superar desafios.", imagem: "img/tarot/sete-de-paus.jpg" },
    { id: 72, nome: "Oito de Paus", significado: "Rapidez, movimento, ação rápida e notícias urgentes.", imagem: "img/tarot/oito-de-paus.jpg" },
    { id: 73, nome: "Nove de Paus", significado: "Resiliência, defesa, cansaço, mas persistência e coragem.", imagem: "img/tarot/nove-de-paus.jpg" },
    { id: 74, nome: "Dez de Paus", significado: "Sobrecarga, responsabilidade, peso e esgotamento extremo.", imagem: "img/tarot/dez-de-paus.jpg" },
    { id: 75, nome: "Valete de Paus", significado: "Exploração, entusiasmo, novas ideias e mensagens criativas.", imagem: "img/tarot/valete-de-paus.jpg" },
    { id: 76, nome: "Cavaleiro de Paus", significado: "Ação, energia, aventura, impulsividade e ir atrás dos seus desejos.", imagem: "img/tarot/cavaleiro-de-paus.jpg" },
    { id: 77, nome: "Rainha de Paus", significado: "Criatividade, paixão, confiança e independência.", imagem: "img/tarot/rainha-de-paus.jpg" },
    { id: 78, nome: "Rei de Paus", significado: "Liderança, visão, inspiração e controle sobre projetos.", imagem: "img/tarot/rei-de-paus.jpg" }
];